import { ShoppingBag, ShoppingCart, Store, Package, Globe } from 'lucide-react';

export const marketplacePlatforms = [
  {
    id: 'amazon',
    name: 'Amazon',
    description: 'Product listing & A+ content',
    icon: ShoppingCart,
    category: 'general',
  },
  {
    id: 'ebay',
    name: 'eBay',
    description: 'Auction & fixed price listings',
    icon: ShoppingBag,
    category: 'general',
  },
  {
    id: 'etsy',
    name: 'Etsy',
    description: 'Handmade & vintage items',
    icon: Store,
    category: 'handmade',
  },
  {
    id: 'walmart',
    name: 'Walmart Marketplace',
    description: 'Retail marketplace integration',
    icon: Store,
    category: 'general',
  },
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'Custom online store',
    icon: Store,
    category: 'platform',
  },
  {
    id: 'aliexpress',
    name: 'AliExpress',
    description: 'Global retail & wholesale',
    icon: Globe,
    category: 'general',
  },
  {
    id: 'wayfair',
    name: 'Wayfair',
    description: 'Home goods & furniture',
    icon: Store,
    category: 'home',
  },
  {
    id: 'newegg',
    name: 'Newegg',
    description: 'Electronics & tech products',
    icon: Package,
    category: 'electronics',
  },
  {
    id: 'bestbuy',
    name: 'Best Buy',
    description: 'Electronics marketplace',
    icon: Store,
    category: 'electronics',
  },
  {
    id: 'homedepot',
    name: 'Home Depot',
    description: 'Home improvement products',
    icon: Store,
    category: 'home',
  },
  {
    id: 'target',
    name: 'Target Plus',
    description: 'Retail marketplace',
    icon: Store,
    category: 'general',
  },
  {
    id: 'wish',
    name: 'Wish',
    description: 'Global marketplace',
    icon: Globe,
    category: 'general',
  },
  {
    id: 'rakuten',
    name: 'Rakuten',
    description: 'Japanese marketplace',
    icon: Globe,
    category: 'general',
  },
  {
    id: 'bonanza',
    name: 'Bonanza',
    description: 'Unique items marketplace',
    icon: Store,
    category: 'general',
  },
  {
    id: 'fruugo',
    name: 'Fruugo',
    description: 'Global marketplace',
    icon: Globe,
    category: 'general',
  },
  {
    id: 'overstock',
    name: 'Overstock',
    description: 'Home goods & furniture',
    icon: Store,
    category: 'home',
  },
  {
    id: 'mercadolibre',
    name: 'MercadoLibre',
    description: 'Latin American marketplace',
    icon: Globe,
    category: 'general',
  },
  {
    id: 'catch',
    name: 'Catch',
    description: 'Australian marketplace',
    icon: Globe,
    category: 'general',
  },
  {
    id: 'flipkart',
    name: 'Flipkart',
    description: 'Indian marketplace',
    icon: Globe,
    category: 'general',
  },
  {
    id: 'lazada',
    name: 'Lazada',
    description: 'Southeast Asian marketplace',
    icon: Globe,
    category: 'general',
  },
];